package com.yuzhiqiang.antigravity.i18n.sections

interface ProviderStrings {
    val providerPresetCategoryAll: String
    val providerPresetCategoryAggregator: String
    val providerPresetCategoryRecommended: String
    val providerPresetCategoryOfficial: String
    val providerPresetCategoryLocalCustom: String
    val providerSearchPlaceholder: String
    val providerTagOfficial: String
    val providerTagAggregator: String
    val providerTagLocal: String
    val providerTagCustom: String
    val providerNameLabel: String
    val providerNamePlaceholder: String
    val providerNameDesc: String
    val providerProtocolLabel: String
    val providerProtocolOpenAIChatDesc: String
    val providerProtocolAnthropicDesc: String
    val providerProtocolGeminiDesc: String
    val providerProtocolOpenAIResponsesDesc: String
    val providerBaseUrlLabel: String
    val providerBaseUrlPlaceholder: String
    val providerBaseUrlDesc: String
    val providerApiKeyLabel: String
    val providerApiKeyPlaceholder: String
    val providerApiKeyDesc: String
    val providerAdvancedSettings: String
    val providerAdvancedAutoGenerated: String
    val providerAdvancedCollapse: String
    val providerCustomModelsEndpoint: String
    val providerCustomCompletionsEndpoint: String
    val providerEndpointAutoInferPlaceholder: String
    val providerStepPreset: String
    val providerStepConnection: String
    val providerStepModels: String
    val providerNextStep: String
    val providerPrevStep: String
    val providerSearchModelsPlaceholder: String
    fun providerFilterAll(count: Int): String
    fun providerFilterSelected(count: Int): String
    fun providerFilterUnselected(count: Int): String
    fun providerSelectAll(count: Int): String
    val providerUnselectAll: String
    val providerViewModelsResponse: String
    fun providerModelsResponseUnavailable(error: String): String
    fun providerNoModelsFound(query: String): String
    val providerNoModelsEmpty: String
    fun providerTestLatency(latencyMs: Long): String
    val providerTestFailed: String
    val providerTestFailureDetailsTitle: String
    val providerTestFailureStatusCode: String
    val providerTestFailureErrorDetails: String
    val providerTestFailureRetry: String
    val providerTestFailureCopy: String
    val providerTestFailureCopied: String
    val providerTestFailureClose: String
    val providerTokenLimitNotSet: String
    fun providerCustomInputTokenTitle(model: String): String
    fun providerCustomOutputTokenTitle(model: String): String
    val providerUnprobedCatalog: String
    val providerTesting: String
    val providerTestBtn: String
    fun providerInputTokenPrefix(label: String): String
    fun providerOutputTokenPrefix(label: String): String
    val providerCustomTokenOption: String
    val providerClearTokenOption: String
    val providerCustomTokenDialogTitle: String
    val providerCustomTokenPlaceholder: String
    val providerCustomTokenHint: String
    fun providerCustomTokenParsed(tokens: String): String
    val providerFetchFailedCheckUrlKey: String
    fun providerFetchFailedWithError(error: String): String
    val providerDiscardConfirmTitle: String
    val providerDiscardConfirmMessage: String
    val providerSkipFetchManualAdd: String
    val providerAddNewModel: String
    val providerManualAddModelTitle: String
    val providerModelIdPlaceholder: String
    val providerModelNamePlaceholder: String
    val providerModelVendorPlaceholder: String
    val providerModelAlreadyExists: String
    val providerModelIdRequired: String
    val providerAddAndSelect: String
    val providerNoModelsEmptyPrompt: String

}

object ProviderStringsZh : ProviderStrings {
    override val providerPresetCategoryAll = "全部"
    override val providerPresetCategoryAggregator = "聚合平台"
    override val providerPresetCategoryRecommended = "常用推荐"
    override val providerPresetCategoryOfficial = "官方厂商"
    override val providerPresetCategoryLocalCustom = "本地/自定义"
    override val providerSearchPlaceholder = "搜索服务..."
    override val providerTagOfficial = "官方"
    override val providerTagAggregator = "聚合平台"
    override val providerTagLocal = "本地"
    override val providerTagCustom = "自定义"
    override val providerNameLabel = "服务商名称"
    override val providerNamePlaceholder = "例如 CLIProxyAPI、公司代理、DeepSeek"
    override val providerNameDesc = "自定义显示名称，用于在模型列表中识别服务商"
    override val providerProtocolLabel = "API 协议"
    override val providerProtocolOpenAIChatDesc = "适用于 /v1/chat/completions；CLIProxyAPI、Sub2API 及标准兼容网关"
    override val providerProtocolAnthropicDesc = "适用于 Anthropic 官方 /v1/messages 协议"
    override val providerProtocolGeminiDesc = "适用于 Google Gemini 官方 generateContent 协议"
    override val providerProtocolOpenAIResponsesDesc = "适用于 OpenAI Responses API 原生结构协议"
    override val providerBaseUrlLabel = "API 地址 (Base URL)"
    override val providerBaseUrlPlaceholder = "例如 https://api.openai.com/v1"
    override val providerBaseUrlDesc = "输入根地址后系统将自动推断补全模型列表与生成对话接口"
    override val providerApiKeyLabel = "API Key"
    override val providerApiKeyPlaceholder = "输入 API Key（无需鉴权可留空）"
    override val providerApiKeyDesc = "如服务无需鉴权可留空"
    override val providerAdvancedSettings = "高级设置（自定义 API 端点）"
    override val providerAdvancedAutoGenerated = "默认由 Base URL 自动推断生成"
    override val providerAdvancedCollapse = "收起"
    override val providerCustomModelsEndpoint = "模型列表接口 URL (自定义)"
    override val providerCustomCompletionsEndpoint = "生成对话接口 URL (自定义)"
    override val providerEndpointAutoInferPlaceholder = "留空自动推断"
    override val providerStepPreset = "选择预设"
    override val providerStepConnection = "网络与鉴权"
    override val providerStepModels = "选择可用模型"
    override val providerNextStep = "下一步"
    override val providerPrevStep = "上一步"
    override val providerSearchModelsPlaceholder = "搜索模型名称或 ID..."
    override fun providerFilterAll(count: Int) = "全部 ($count)"
    override fun providerFilterSelected(count: Int) = "已选 ($count)"
    override fun providerFilterUnselected(count: Int) = "未选 ($count)"
    override fun providerSelectAll(count: Int) = "全选 ($count)"
    override val providerUnselectAll = "取消全选"
    override val providerViewModelsResponse = "查看模型列表数据"
    override fun providerModelsResponseUnavailable(error: String) = "未能读取模型列表数据：$error"
    override fun providerNoModelsFound(query: String) = "未搜索到匹配「$query」的模型"
    override val providerNoModelsEmpty = "当前筛选下暂无模型"
    override fun providerTestLatency(latencyMs: Long) = "${latencyMs}ms"
    override val providerTestFailed = "失败"
    override val providerTestFailureDetailsTitle = "模型连通性测试失败"
    override val providerTestFailureStatusCode = "HTTP 状态码"
    override val providerTestFailureErrorDetails = "错误响应详情"
    override val providerTestFailureRetry = "重新测试"
    override val providerTestFailureCopy = "复制错误信息"
    override val providerTestFailureCopied = "已复制到剪贴板"
    override val providerTestFailureClose = "关闭"
    override val providerTokenLimitNotSet = "未设置"
    override fun providerCustomInputTokenTitle(model: String) = "自定义模型上下文上限 · $model"
    override fun providerCustomOutputTokenTitle(model: String) = "自定义最大输出 · $model"
    override val providerUnprobedCatalog = "未获取模型列表"
    override val providerTesting = "测试中"
    override val providerTestBtn = "测试"
    override fun providerInputTokenPrefix(label: String) = "模型上下文：$label"
    override fun providerOutputTokenPrefix(label: String) = "最大输出：$label"
    override val providerCustomTokenOption = "自定义数值..."
    override val providerClearTokenOption = "清除 (设为未设置)"
    override val providerCustomTokenDialogTitle = "自定义 Token 上限"
    override val providerCustomTokenPlaceholder = "例如：128K, 1M, 200000"
    override val providerCustomTokenHint = "支持 128K / 1M / 纯数字 等格式"
    override fun providerCustomTokenParsed(tokens: String) = "解析为: $tokens tokens"
    override val providerFetchFailedCheckUrlKey = "未能获取模型列表，请检查 API 地址与 API Key 是否正确"
    override fun providerFetchFailedWithError(error: String) = "获取模型列表失败: $error"
    override val providerDiscardConfirmTitle = "放弃未保存的更改？"
    override val providerDiscardConfirmMessage = "当前正在编辑的服务商配置尚未保存，退出后更改将丢失。"
    override val providerSkipFetchManualAdd = "跳过探测，手动配置模型"
    override val providerAddNewModel = "添加模型"
    override val providerManualAddModelTitle = "手动添加自定义模型"
    override val providerModelIdPlaceholder = "模型 ID (如 gpt-4o, claude-3-7-sonnet)"
    override val providerModelNamePlaceholder = "显示名称 (选填)"
    override val providerModelVendorPlaceholder = "厂商名称 (选填，如 OpenAI)"
    override val providerModelAlreadyExists = "该模型 ID 已在列表中"
    override val providerModelIdRequired = "模型 ID 不能为空"
    override val providerAddAndSelect = "添加并选中"
    override val providerNoModelsEmptyPrompt = "暂无模型，可点击上方「添加模型」手动录入"

}

object ProviderStringsEn : ProviderStrings {
    override val providerPresetCategoryAll = "All"
    override val providerPresetCategoryAggregator = "Gateways"
    override val providerPresetCategoryRecommended = "Recommended"
    override val providerPresetCategoryOfficial = "Official Vendors"
    override val providerPresetCategoryLocalCustom = "Local / Custom"
    override val providerSearchPlaceholder = "Search providers..."
    override val providerTagOfficial = "Official"
    override val providerTagAggregator = "Gateway"
    override val providerTagLocal = "Local"
    override val providerTagCustom = "Custom"
    override val providerNameLabel = "Upstream Provider Name"
    override val providerNamePlaceholder = "e.g. CLIProxyAPI, Company Gateway, DeepSeek"
    override val providerNameDesc = "Custom display name used to identify the source in routes and model lists"
    override val providerProtocolLabel = "API Protocol"
    override val providerProtocolOpenAIChatDesc = "For /v1/chat/completions; CLIProxyAPI, Sub2API and standard gateways"
    override val providerProtocolAnthropicDesc = "For Anthropic official /v1/messages protocol"
    override val providerProtocolGeminiDesc = "For Google Gemini official generateContent protocol"
    override val providerProtocolOpenAIResponsesDesc = "For OpenAI Responses API native structure protocol"
    override val providerBaseUrlLabel = "API Base URL"
    override val providerBaseUrlPlaceholder = "e.g. https://api.openai.com/v1"
    override val providerBaseUrlDesc = "Entering base URL automatically infers model list and generation endpoints"
    override val providerApiKeyLabel = "API Key"
    override val providerApiKeyPlaceholder = "Enter API Key (leave blank if no auth required)"
    override val providerApiKeyDesc = "Leave blank if upstream service requires no authentication"
    override val providerAdvancedSettings = "Advanced Settings (Custom Endpoint URLs)"
    override val providerAdvancedAutoGenerated = "Auto-generated from Base URL by default"
    override val providerAdvancedCollapse = "Collapse"
    override val providerCustomModelsEndpoint = "Model List Endpoint (Custom)"
    override val providerCustomCompletionsEndpoint = "Completions Endpoint (Custom)"
    override val providerEndpointAutoInferPlaceholder = "Leave blank to auto-infer"
    override val providerStepPreset = "Select Preset"
    override val providerStepConnection = "Connection"
    override val providerStepModels = "Select Models"
    override val providerNextStep = "Next"
    override val providerPrevStep = "Back"
    override val providerSearchModelsPlaceholder = "Search model name or ID..."
    override fun providerFilterAll(count: Int) = "All ($count)"
    override fun providerFilterSelected(count: Int) = "Selected ($count)"
    override fun providerFilterUnselected(count: Int) = "Unselected ($count)"
    override fun providerSelectAll(count: Int) = "Select All ($count)"
    override val providerUnselectAll = "Deselect All"
    override val providerViewModelsResponse = "View Model List Data"
    override fun providerModelsResponseUnavailable(error: String) = "Unable to read model list data: $error"
    override fun providerNoModelsFound(query: String) = "No models matched \"$query\""
    override val providerNoModelsEmpty = "No models in current filter"
    override fun providerTestLatency(latencyMs: Long) = "${latencyMs}ms"
    override val providerTestFailed = "Failed"
    override val providerTestFailureDetailsTitle = "Model Test Failed"
    override val providerTestFailureStatusCode = "HTTP Status Code"
    override val providerTestFailureErrorDetails = "Error Details"
    override val providerTestFailureRetry = "Retry Test"
    override val providerTestFailureCopy = "Copy Error"
    override val providerTestFailureCopied = "Copied to Clipboard"
    override val providerTestFailureClose = "Close"
    override val providerTokenLimitNotSet = "Not Set"
    override fun providerCustomInputTokenTitle(model: String) = "Custom Context Window · $model"
    override fun providerCustomOutputTokenTitle(model: String) = "Custom Max Output · $model"
    override val providerUnprobedCatalog = "Unprobed"
    override val providerTesting = "Testing"
    override val providerTestBtn = "Test"
    override fun providerInputTokenPrefix(label: String) = "Context window: $label"
    override fun providerOutputTokenPrefix(label: String) = "Max output: $label"
    override val providerCustomTokenOption = "Custom value..."
    override val providerClearTokenOption = "Clear (Set to Not Set)"
    override val providerCustomTokenDialogTitle = "Custom Token Limit"
    override val providerCustomTokenPlaceholder = "e.g. 128K, 1M, 200000"
    override val providerCustomTokenHint = "Supports 128K / 1M / numeric formats"
    override fun providerCustomTokenParsed(tokens: String) = "Parsed as: $tokens tokens"
    override val providerFetchFailedCheckUrlKey = "Failed to fetch model catalog. Please check Base URL and API Key"
    override fun providerFetchFailedWithError(error: String) = "Failed to fetch models: $error"
    override val providerDiscardConfirmTitle = "Discard unsaved changes?"
    override val providerDiscardConfirmMessage =
        "The provider configuration has not been saved. Changes will be lost upon exit."
    override val providerSkipFetchManualAdd = "Skip fetch, add models manually"
    override val providerAddNewModel = "Add Model"
    override val providerManualAddModelTitle = "Manually Add Custom Model"
    override val providerModelIdPlaceholder = "Model ID (e.g. gpt-4o, claude-3-7-sonnet)"
    override val providerModelNamePlaceholder = "Display name (optional)"
    override val providerModelVendorPlaceholder = "Vendor (optional, e.g. OpenAI)"
    override val providerModelAlreadyExists = "Model ID already exists in the list"
    override val providerModelIdRequired = "Model ID is required"
    override val providerAddAndSelect = "Add & Select"
    override val providerNoModelsEmptyPrompt = "No models available. Click \"Add Model\" above to add one manually."

}
