package com.yuzhiqiang.antigravity.host.windows

import com.yuzhiqiang.antigravity.logging.AppLog
import java.io.File
import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Windows 平台专用语言服务包装器 (language_server.exe Shim)。
 *
 * Antigravity App 在 Windows 上通过 Electron 直接调用 resources/bin/language_server.exe，
 * 并在启动时通过 fs.existsSync 严格检查该二进制文件。
 * 本对象提供轻量级原生 PE 可执行程序（内置 Base64 编码，无第三方依赖），
 * 负责拦截并改写 --cloud_code_endpoint 参数重定向至本地代理端点，
 * 并将所有标准 I/O 句柄透传给 language_server.original.exe。
 */
object WindowsShimBinary {

    const val SHIM_MARKER = "ANTIGRAVITY_STUDIO_MANAGED_SHIM"

    private val SHIM_MARKER_BYTES_UTF8 = SHIM_MARKER.toByteArray(Charsets.UTF_8)
    private val SHIM_MARKER_BYTES_UTF16LE = SHIM_MARKER.toByteArray(Charsets.UTF_16LE)

    @OptIn(ExperimentalEncodingApi::class)
    fun getShimBinaryBytes(): ByteArray {
        return Base64.decode(SHIM_BASE64)
    }

    /**
     * 检测目标文件是否是 Studio 托管的 Windows Shim 二进制可执行文件。
     */
    fun isShimBinary(file: File): Boolean {
        if (!file.exists() || !file.isFile || file.length() < 512) return false
        return runCatching {
            file.inputStream().use { input ->
                val bufferSize = minOf(file.length().toInt(), 16384)
                val buffer = ByteArray(bufferSize)
                val read = input.read(buffer)
                if (read <= 0) return@use false
                val slice = buffer.copyOf(read)
                containsSequence(slice, SHIM_MARKER_BYTES_UTF8) ||
                        containsSequence(slice, SHIM_MARKER_BYTES_UTF16LE)
            }
        }.getOrDefault(false)
    }

    /**
     * 将 Shim 可执行程序写入目标路径。
     */
    fun writeShimBinary(targetFile: File): Boolean {
        return try {
            val bytes = getShimBinaryBytes()
            val tempFile = File(targetFile.parentFile, "${targetFile.name}.tmp_${System.currentTimeMillis()}")
            tempFile.writeBytes(bytes)
            if (targetFile.exists()) {
                targetFile.delete()
            }
            val renamed = tempFile.renameTo(targetFile)
            if (!renamed) {
                targetFile.writeBytes(bytes)
                tempFile.delete()
            }
            isShimBinary(targetFile)
        } catch (error: Exception) {
            AppLog.e("Host/WindowsShim", error) { "写入 Windows Shim 二进制失败：${targetFile.absolutePath}" }
            false
        }
    }

    private fun containsSequence(source: ByteArray, target: ByteArray): Boolean {
        if (target.isEmpty() || source.size < target.size) return false
        val maxStart = source.size - target.size
        for (i in 0..maxStart) {
            var match = true
            for (j in target.indices) {
                if (source[i + j] != target[j]) {
                    match = false
                    break
                }
            }
            if (match) return true
        }
        return false
    }

    @Suppress("SpellCheckingInspection")
    private const val SHIM_BASE64 =
        "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFt" +
        "IGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAAZIYCAAyak2oAAAAAAAAAAPAAIgALAgsAAA4AAAAGAAAAAAAAAAAAAAAgAAAAAABA" +
        "AQAAAAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAABgAAAAAgAAAAAAAAMAQIUAAEAAAAAAAABAAAAAAAAAAAAQAAAAAAAAIAAAAAAAAAAAAAAQAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAABAAAAIBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAgAABIAAAAAAAAAAAAAAAudGV4dAAAAMgNAAAAIAAAAA4AAAACAAAAAAAAAAAAAAAAAAAgAABgLnJzcmMAAAAIBQAAAEAAAAAG" +
        "AAAAEAAAAAAAAAAAAAAAAAAAQAAAQC5yZWxvYwAAAAAAAABgAAAAAAAAABYAAAAAAAAAAAAAAAAAAEAAAEJIAAAAAgAFAPwjAADMCQAAAQAAAAEAAAYAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABswAwDWAAAAAQAAESgDAAAKbwQAAAoKBnIBAABwKAUAAAoLBygG" +
        "AAAKLR0oBwAACnI7AABwBygIAAAKbwkAAAoXEwndlwAAAAYoAgAABgwCCCgDAAAGDXKtAABwCW8KAAAKKAsAAAoTBHMMAAAKEwcRBwdvDQAAChEHEQRvDgAA" +
        "ChEHFm8PAAAKEQcTBREFKBAAAAoTBhEGLQUXEwneQBEGbxEAAAoRBm8SAAAKEwneLhEGLAcRBm8TAAAK3BMIKAcAAApysQAAcBEIbxQAAAooCAAACm8JAAAK" +
        "FxMJ3gARCSoAAAEcAAACAIoAG6UADAAAAAAAAAAAsbEAIg4AAAEbMAIAqQAAAAIAABFy5QAAcCgVAAAKCgYoFgAACi0HBm8XAAAKKgJyAwEAcCgFAAAKCwco" +
        "BgAACiweBygYAAAKKBkAAApvFwAACgoGKBYAAAotBQYTBd5a3gMm3gB+GgAACnI9AQBwbxsAAAoMCCwrCHLlAABwbxwAAAoNCSwcCW8dAAAKbxcAAAoTBBEE" +
        "KBYAAAotBhEEEwXeF94KCCwGCG8TAAAK3N4DJt4AclUBAHAqEQUqAAAAASgAAAAAGgA0TgADAQAAAQIAYQAwkQAKAAAAAAAAUQBMnQADAQAAARMwAwC4AAAA" +
        "AwAAEXMeAAAKChYLFgwWDRYTBCt7AhEEmhMFEQVygQEAcCgfAAAKLAIXDQcsEgYDKAQAAAZvIAAAChYLFwwrShEFcpEBAHAoHwAACiwMBhEFbyAAAAoXCysw" +
        "EQVyvQEAcG8hAAAKLBUGcr0BAHADKAgAAApvIAAAChcMKw0GEQUoBAAABm8gAAAKEQQXWBMEEQQCjmk/e////wktHQgtGgctFwZykQEAcG8gAAAKBgMoBAAA" +
        "Bm8gAAAKBioTMAQA9AAAAAQAABECKBYAAAosBnLrAQBwKgJyrQAAcG8iAAAKLTYCcvEBAHBvIgAACi0pAnL1AQBwbyIAAAotHAJy+QEAcG8iAAAKLQ8Ccv0B" +
        "AHBvIgAACi0CAipzIwAACgoGHyJvJAAACiYWCyt3FgwrCAgXWAwHF1gLBwJvJQAACi8LAgdvJgAACh9cLuQHAm8lAAAKMw4GH1wIGFpvJwAACiYrSQIHbyYA" +
        "AAofIjMZBh9cCBhaF1hvJwAACiYGHyJvJAAACiYrGAYfXAhvJwAACiYGAgdvJgAACm8kAAAKJgcXWAsHAm8lAAAKMoAGHyJvJAAACiYGbx0AAAoqHgIoKAAA" +
        "CipCU0pCAQABAAAAAAAMAAAAdjQuMC4zMDMxOQAAAAAFAGwAAACcAgAAI34AAAgDAABoAwAAI1N0cmluZ3MAAAAAcAYAAAQCAAAjVVMAdAgAABAAAAAjR1VJ" +
        "RAAAAIQIAABIAQAAI0Jsb2IAAAAAAAAAAgAAAVcdAggJAAAAAPolMwAWAAABAAAAEwAAAAIAAAABAAAABQAAAAUAAAAoAAAAAQAAAAIAAAAEAAAAAQAAAAEA" +
        "AAACAAAAAAAKAAEAAAAAAAYAOgAzAAYAfgBjAAYA4QDBAAYAAQHBAAYAMwEzAAYAawFhAQYAeAFhAQYAhAEzAAYAjAFhAQYAoQEzAAoA2QHGAQoAGQLGAQYA" +
        "QAIzAAYAVAIzAAYAagIzAAYArAKgAgYA2gLKAgYA4wLKAgYAPAOgAgAAAAABAAAAAAABAAEAAQAQACIAAAAFAAEAAQBRgEEACgBQIAAAAACWAE0ATAABAFAh" +
        "AAAAAJEAUgBSAAIAMCIAAAAAkQCFAFcAAwD0IgAAAACRAJYAUgAFAPQjAAAAAIYYoABiAAYAAAABAKYAAAABAKsAAAABAKYAAAACALMAAAABAL0AGQCgAGYA" +
        "IQCgAGIAKQA9AWsAKQBPAXAAMQBwAXQAOQB9AXoAQQCXAX8AUQCoAXQASQCvAYQADAC5AY8AUQDBAZUAWQCgAGIAWQDqAYQAWQD3AYQAWQAFApwAYQAhAqEA" +
        "YQAnAmIAYQAzAqgAaQBMAmIAcQBeAnAAeQB2AlIAUQCNAnoAUQCbAnAAgQC1AsEAOQC+AsYAiQDvAs0AkQD7AtEAkQAGA9cACQAPA3AADACgAGIAUQAYA+YA" +
        "DAAkA+wAUQAoA/IAUQAzA/IAmQCgAGIAmQBKAwQBUQBRA6gAUQBcAwoBmQBKAw8BCQCgAGIADgAEAA0ALgALAB0BLgATACYBrADcAPcAFgGJAASAAAAAAAAA" +
        "AAAAAAAAAAAAAB8BAAAEAAAAAAAAAAAAAAABACoAAAAAAAQAAAAAAAAAAAAAAAEAMwAAAAAAAAAAAAA8TW9kdWxlPgBsYW5ndWFnZV9zZXJ2ZXJfeDY0LmV4" +
        "ZQBQcm9ncmFtAG1zY29ybGliAFN5c3RlbQBPYmplY3QAU0hJTV9NQVJLRVIATWFpbgBSZXNvbHZlVGFyZ2V0VXJsAFN5c3RlbS5Db2xsZWN0aW9ucy5HZW5l" +
        "cmljAExpc3RgMQBQcm9jZXNzQXJndW1lbnRzAEVzY2FwZUFyZwAuY3RvcgBhcmdzAGJhc2VEaXIAdGFyZ2V0VXJsAGFyZwBTeXN0ZW0uUnVudGltZS5Db21w" +
        "aWxlclNlcnZpY2VzAENvbXBpbGF0aW9uUmVsYXhhdGlvbnNBdHRyaWJ1dGUAUnVudGltZUNvbXBhdGliaWxpdHlBdHRyaWJ1dGUAbGFuZ3VhZ2Vfc2VydmVy" +
        "X3g2NABBcHBEb21haW4AZ2V0X0N1cnJlbnREb21haW4AZ2V0X0Jhc2VEaXJlY3RvcnkAU3lzdGVtLklPAFBhdGgAQ29tYmluZQBGaWxlAEV4aXN0cwBDb25z" +
        "b2xlAFRleHRXcml0ZXIAZ2V0X0Vycm9yAFN0cmluZwBDb25jYXQAV3JpdGVMaW5lAFRvQXJyYXkASm9pbgBTeXN0ZW0uRGlhZ25vc3RpY3MAUHJvY2Vzc1N0" +
        "YXJ0SW5mbwBzZXRfRmlsZU5hbWUAc2V0X0FyZ3VtZW50cwBzZXRfVXNlU2hlbGxFeGVjdXRlAFByb2Nlc3MAU3RhcnQAV2FpdEZvckV4aXQAZ2V0X0V4aXRD" +
        "b2RlAElEaXNwb3NhYmxlAERpc3Bvc2UARXhjZXB0aW9uAGdldF9NZXNzYWdlAEVudmlyb25tZW50AEdldEVudmlyb25tZW50VmFyaWFibGUASXNOdWxsT3JF" +
        "bXB0eQBUcmltAFN5c3RlbS5UZXh0AEVuY29kaW5nAGdldF9VVEY4AFJlYWRBbGxUZXh0AE1pY3Jvc29mdC5XaW4zMgBSZWdpc3RyeQBSZWdpc3RyeUtleQBD" +
        "dXJyZW50VXNlcgBPcGVuU3ViS2V5AEdldFZhbHVlAFRvU3RyaW5nAG9wX0VxdWFsaXR5AEFkZABTdGFydHNXaXRoAENvbnRhaW5zAFN0cmluZ0J1aWxkZXIA" +
        "QXBwZW5kAGdldF9MZW5ndGgAZ2V0X0NoYXJzAAAAADlsAGEAbgBnAHUAYQBnAGUAXwBzAGUAcgB2AGUAcgAuAG8AcgBpAGcAaQBuAGEAbAAuAGUAeABlAABx" +
        "WwBBAG4AdABpAGcAcgBhAHYAaQB0AHkAIABTAGgAaQBtACAARQByAHIAbwByAF0AIABPAHIAaQBnAGkAbgBhAGwAIABlAHgAZQBjAHUAdABhAGIAbABlACAA" +
        "bgBvAHQAIABmAG8AdQBuAGQAOgAgAAADIAAAM1sAQQBuAHQAaQBnAHIAYQB2AGkAdAB5ACAAUwBoAGkAbQAgAEUAcgByAG8AcgBdACAAAB1DAEwATwBVAEQA" +
        "XwBDAE8ARABFAF8AVQBSAEwAADlsAGEAbgBnAHUAYQBnAGUAXwBzAGUAcgB2AGUAcgBfAGUAbgBkAHAAbwBpAG4AdAAuAHQAeAB0AAAXRQBuAHYAaQByAG8A" +
        "bgBtAGUAbgB0AAAraAB0AHQAcAA6AC8ALwAxADIANwAuADAALgAwAC4AMQA6ADgAMwAyADEAAA8tAC0AcwB0AGEAbQBwAAErLQAtAGMAbABvAHUAZABfAGMA" +
        "bwBkAGUAXwBlAG4AZABwAG8AaQBuAHQAAS0tAC0AYwBsAG8AdQBkAF8AYwBvAGQAZQBfAGUAbgBkAHAAbwBpAG4AdAA9AAEFIgAiAAADCQAAAyIAAAMKAAAD" +
        "DQAAAAAAFkvBOiV6rk2+wYJJSM6FlAAIt3pcVhk04IkCBg4+QQBOAFQASQBHAFIAQQBWAEkAVABZAF8AUwBUAFUARABJAE8AXwBNAEEATgBBAEcARQBEAF8A" +
        "UwBIAEkATQAFAAEIHQ4EAAEODgoAAhUSCQEOHQ4OAyAAAQQgAQEIBAAAEhUDIAAOBQACDg4OBAABAg4EAAASJQQgAQEOBRUSCQEOBSAAHRMABgACDg4dDgQg" +
        "AQECBgABEjESLQMgAAgUBwoODg4VEgkBDg4SLRIxEi0SOQgEAAASQQYAAg4OEkEDBhJJBSABEkkOBCABHA4JBwYODhJJHA4OBQACAg4OBSABARMABCABAg4M" +
        "BwYVEgkBDgICAggOBSABEk0DBCABAwgGIAISTQMIBgcDEk0ICAgBAAgAAAAAAB4BAAEAVAIWV3JhcE5vbkV4Y2VwdGlvblRocm93cwEAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAQAAAAIAAAgBgAAAA4AACAAAAAAAAAAAAAAAAA" +
        "AAABAAEAAABQAACAAAAAAAAAAAAAAAAAAAABAAEAAABoAACAAAAAAAAAAAAAAAAAAAABAAAAAACAAAAAAAAAAAAAAAAAAAAAAAABAAAAAACQAAAAoEAAAHQC" +
        "AAAAAAAAAAAAABhDAADqAQAAAAAAAAAAAAB0AjQAAABWAFMAXwBWAEUAUgBTAEkATwBOAF8ASQBOAEYATwAAAAAAvQTv/gAAAQAAAAAAAAAAAAAAAAAAAAAA" +
        "PwAAAAAAAAAEAAAAAQAAAAAAAAAAAAAAAAAAAEQAAAABAFYAYQByAEYAaQBsAGUASQBuAGYAbwAAAAAAJAAEAAAAVAByAGEAbgBzAGwAYQB0AGkAbwBuAAAA" +
        "AAAAALAE1AEAAAEAUwB0AHIAaQBuAGcARgBpAGwAZQBJAG4AZgBvAAAAsAEAAAEAMAAwADAAMAAwADQAYgAwAAAALAACAAEARgBpAGwAZQBEAGUAcwBjAHIA" +
        "aQBwAHQAaQBvAG4AAAAAACAAAAAwAAgAAQBGAGkAbABlAFYAZQByAHMAaQBvAG4AAAAAADAALgAwAC4AMAAuADAAAABQABgAAQBJAG4AdABlAHIAbgBhAGwA" +
        "TgBhAG0AZQAAAGwAYQBuAGcAdQBhAGcAZQBfAHMAZQByAHYAZQByAF8AeAA2ADQALgBlAHgAZQAAACgAAgABAEwAZQBnAGEAbABDAG8AcAB5AHIAaQBnAGgA" +
        "dAAAACAAAABYABgAAQBPAHIAaQBnAGkAbgBhAGwARgBpAGwAZQBuAGEAbQBlAAAAbABhAG4AZwB1AGEAZwBlAF8AcwBlAHIAdgBlAHIAXwB4ADYANAAuAGUA" +
        "eABlAAAANAAIAAEAUAByAG8AZAB1AGMAdABWAGUAcgBzAGkAbwBuAAAAMAAuADAALgAwAC4AMAAAADgACAABAEEAcwBzAGUAbQBiAGwAeQAgAFYAZQByAHMA" +
        "aQBvAG4AAAAwAC4AMAAuADAALgAwAAAAAAAAAO+7vzw/eG1sIHZlcnNpb249IjEuMCIgZW5jb2Rpbmc9IlVURi04IiBzdGFuZGFsb25lPSJ5ZXMiPz4NCjxh" +
        "c3NlbWJseSB4bWxucz0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTphc20udjEiIG1hbmlmZXN0VmVyc2lvbj0iMS4wIj4NCiAgPGFzc2VtYmx5SWRlbnRp" +
        "dHkgdmVyc2lvbj0iMS4wLjAuMCIgbmFtZT0iTXlBcHBsaWNhdGlvbi5hcHAiLz4NCiAgPHRydXN0SW5mbyB4bWxucz0idXJuOnNjaGVtYXMtbWljcm9zb2Z0" +
        "LWNvbTphc20udjIiPg0KICAgIDxzZWN1cml0eT4NCiAgICAgIDxyZXF1ZXN0ZWRQcml2aWxlZ2VzIHhtbG5zPSJ1cm46c2NoZW1hcy1taWNyb3NvZnQtY29t" +
        "OmFzbS52MyI+DQogICAgICAgIDxyZXF1ZXN0ZWRFeGVjdXRpb25MZXZlbCBsZXZlbD0iYXNJbnZva2VyIiB1aUFjY2Vzcz0iZmFsc2UiLz4NCiAgICAgIDwv" +
        "cmVxdWVzdGVkUHJpdmlsZWdlcz4NCiAgICA8L3NlY3VyaXR5Pg0KICA8L3RydXN0SW5mbz4NCjwvYXNzZW1ibHk+DQoAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
}
